### ISSUE TITLE
Update docs: link is broken

### ISSUE THREAD

**Issue by sgahlot** [RedHatQuickCourses/devhub-build#11]
In the `Software Templates -> Built-in Actions` section of `[Building Developer Portals with Red Hat Developer Hub](https://redhatquickcourses.github.io/devhub-build/devhub-build/1/index.html)`, the link to the complete list of actions is broken.

<img width="1436" alt="Screenshot 2024-03-14 at 2 37 33 PM" src="https://github.com/RedHatQuickCourses/devhub-build/assets/2349910/6e12ed55-eaa1-455d-8535-ef0e357654f2">

**Comment by rsriniva** [comment]
Oh. Sorry if this was confusing, You have to replace RHDH_URL with *your* instance of RHDP classroom. The unique one with GUID in the dynamic.redhatworkshops.io DNS domain.
