### ISSUE TITLE
url missing

### ISSUE THREAD

**Issue by mcombi** [RedHatQuickCourses/devhub-build#12]
https://redhatquickcourses.github.io/devhub-build/devhub-build/1/chapter1/templates.html 

In the paragraph the correct URL is missing
Built-in Actions

  Steps rely on a number of built-in actions that perform some of the common tasks when instantiating the template. A complete list of actions is available at the **https://rhdh_url/create/actions.** This page displays all the available actions that you can reuse in your template, along with a detailed description of the inputs to the actions.

**Comment by mcombi** [comment]
Ok, you are right. I didn't get the point. Maybe it is possible to clarify on the page?

**Comment by rsriniva** [comment]
Thanks @mcombi . I added another sentence to the text to replace the URL
