### ISSUE TITLE
Deleting a Template: how to?

### ISSUE THREAD

**Issue by chantallengua** [RedHatQuickCourses/devhub-build#13]
Hello, in the very end (step 14) of the [Software Templates page](https://redhatquickcourses.github.io/devhub-build/devhub-build/1/chapter1/templates.html), when asked to "Finally, delete the react-ssr-template template", there is no explanation of how to delete a template, and in the Developer Hub I can't find a way to do it.

**Comment by rsriniva** [comment]
Please follow instructions in https://redhatquickcourses.github.io/devhub-build/devhub-build/1/chapter1/catalog.html#_lab_1_populating_the_catalog_manually Step #10 to unregister components.

**Comment by rsriniva** [comment]
A Template is a type of RHDH component. Use the drop-down filters to search and find your template and then unregister it.

**Comment by rsriniva** [comment]
@chantallengua - did you get a chance to try my suggestion?

**Comment by chantallengua** [comment]
Yes it works thank you!
