### ISSUE TITLE
Section Tekton plugin

### ISSUE THREAD

**Issue by mcombi** [RedHatQuickCourses/devhub-build#15]
Step 4: 
Typically, pipelines are triggered by a Git repository commit, but for the purposes of this lab, we can launch the pipeline using the oc CLI and YAML files describing PipelineRun resources. Inspect the https://github.com/RedHatQuickCourses/devhub-qc-apps/blob/main/ci-cd/run-ok.yaml and https://github.com/RedHatQuickCourses/devhub-qc-apps/blob/main/ci-cd/run-ok.yaml file. These simulate a successful and failed pipeline run respectively.

There is linked two times the run-ok.yaml instead of one ok and one fail

**Comment by rsriniva** [comment]
ouch! typo error. will release a fix soon. I am updating instructions for RHDH 1.2. Thanks!

**Comment by rsriniva** [comment]
fixed and updated in latest course that has been updated and tested against RHDH 1..2.1
