### ISSUE TITLE
Section ArgoCd - unable to deploy

### ISSUE THREAD

**Issue by mcombi** [RedHatQuickCourses/devhub-build#16]
I've installed Openshift Gitops Operator, in the right namespace as per instructions in prerequisites. 

Without adding: oc adm policy add-cluster-role-to-user cluster-admin -z openshift-gitops-argocd-application-controller -n openshift-gitops it is not possible to let argo deploy applications. 
![Screenshot from 2024-04-15 21-47-58](https://github.com/RedHatQuickCourses/devhub-build/assets/100132715/0770dc7f-4c67-4e63-abf3-a1769ec7f2fa)

**Comment by rsriniva** [comment]
fixed and updated in latest course that has been updated and tested against RHDH 1..2.1. Please see latest instructions in the GitOps section of the course. The configuration has changed slightly from older versions
